### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gamzonneveld** [willemstoker/aps-to-pvoutput#1]
Hello,

I try to run app-to-pvoutput but I got the following error:

Traceback (most recent call last):
  File "/volume1/web/ema2pvoutput/apstopvoutput.py", line 70, in <module>
    timesstring = rootdict.get("data").get("time")
AttributeError: 'NoneType' object has no attribute 'get'

I hope you can help me.

Guido

**Comment by willemstoker** [comment]
You probably did not get the expected date returned. Try to display the
returned data, maybe it will help.

Greetings

Op di 30 jul. 2019 23:26 schreef gamzonneveld <notifications@github.com>:

**Comment by gamzonneveld** [comment]
Thanks for the respons.
It was my fault, the ECU number was wrong.

Guido
