### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by krizzziz** [willemstoker/aps-to-pvoutput#3]
Hi,

I just ran the script and I have the following error. Anyone know why?

`Traceback (most recent call last):
  File "./apstopvoutput.py", line 67, in <module>
    writeLastUpdate('00:00') #create file for the first time
  File "./apstopvoutput.py", line 29, in writeLastUpdate
    f = open(LAST_UPDATE_FILE,"w+")
IOError: [Errno 2] No such file or directory: '<path/file>'`

**Comment by willemstoker** [comment]
you should fill in a filename

Op vr 2 aug. 2019 07:19 schreef krizzziz <notifications@github.com>:

**Comment by krizzziz** [comment]
Oeps....

While you made it so easy. Thanks for the support! Done and working :)
